version: '3.8'

services:
  backend:
    image: api-server
    build: .
    ports:
      - 8080:8080
    volumes:
      - ./:/usr/src/pocapi
      - /usr/src/pocapi/node_modules
    env_file:
      - ./.env
    depends_on:
      - mongodb
    networks:
      - pocapi-internal
  
  mongodb:
    image: mongo
    container_name: mongodb
    volumes:
      - data:/data/db
    networks:
      - pocapi-internal

networks:
  pocapi-internal:

volumes:
  data:
